### ISSUE TITLE
wrong url encoding

### ISSUE THREAD

**Issue by lcaouen** [ornl-epics/dbwr#16]
URL links with action button widgets is not correct in DBWR.
The link is HTML encoded whereas it shouldn't.

in bob file we have :
```
  <widget type="action_button" version="3.0.0">
    <name>Button_OpenApplianceHydro</name>
    <actions>
      <action type="open_webpage">
        <url>http://132.166.36.229:17668/retrieval/ui/viewer/archViewer.html?pv=BAT472:DEV01:rh&amp;pv=BAT472:DEV02:rh&amp;pv=BAT472:DEV03:rh&amp;pv=BAT472:DEV04:rh&amp;pv=BAT472:DEV05:rh</url>
        <description>Open Web Page</description>
      </action>
    </actions>
    <text>Voir les courbes des hydrométries</text>
    <x>80</x>
    <y>112</y>
    <width>230</width>
    <tooltip>$(actions)</tooltip>
  </widget>

```
In dbwr, the link is : http://132.166.36.229:17668/retrieval/ui/viewer/archViewer.html?pv=BAT472:DEV01:tt&amp;pv=BAT472:DEV02:tt&amp;pv=BAT472:DEV03:tt&amp;pv=BAT472:DEV04:tt&amp;pv=BAT472:DEV05:tt
whereas it should be : http://132.166.36.229:17668/retrieval/ui/viewer/archViewer.html?pv=BAT472:DEV01:tt&pv=BAT472:DEV02:tt&pv=BAT472:DEV03:tt&pv=BAT472:DEV04:tt&pv=BAT472:DEV05:tt

**Comment by kasemir** [comment]
Should be fixed by your PR, thanks!
