### ISSUE TITLE
Databrowser: time span doesn't work properly when there is more than one plot

### ISSUE THREAD

**Issue by konrad-gajewski** [ornl-epics/dbwr#21]
When there is more than one plot on the screen and they have different time spans the second plot's time span jumps between it's own time span and the span of the first plot.
It would be nice if the position of the Setting pop-up would be connected to the relevant plot widget.

**Comment by kasemir** [comment]
Looks like the error is in https://github.com/ornl-epics/dbwr/blob/main/src/main/webapp/widgets/databrowser.js
While most of the info is specific to the widget (`widget.data("traces")`), the start and end time is held within the global `_db_plot_options.xaxis.min` and `_db_plot_options.xaxis.max`.
So each widget needs its own copy of the `_db_plot_options`.
Can you fix that?

**Comment by konrad-gajewski** [comment]
I’m not a JS programmer but I can have a look and try to fix it next week when I’m back in the office. Konrad. Skickat från min iPhone6 mars 2023 kl. 16:04 skrev Kay Kasemir ***@***.***>:﻿




Looks like the error is in 
https://github.com/ornl-epics/dbwr/blob/main/src/main/webapp/widgets/databrowser.js
While most of the info is specific to the widget (widget.data("traces")), the start and end time is held within the global
_db_plot_options.xaxis.min and 
_db_plot_options.xaxis.max.
So each widget needs its own copy of the _db_plot_options.
Can you fix that?
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you authored the thread.Message
 ID: ***@***.***>




VARNING: Klicka inte på länkar och öppna inte bilagor om du inte känner igen avsändaren och vet att innehållet är säkert.
CAUTION: Do not click on links or open attachments unless you recognise the sender and know the content is safe.

**Comment by kasemir** [comment]
Has been fixed
